### F1 Circuit Complexity Index

Formula 1 is the peak of motorsport where only the best drivers from around the world are allowed behind the wheel and onto the track. Each track is unique and has its own set of technical and physical challeneges the drivers must adapt to. This analysis looks to develop a composite indicator designed to quantify the difficulty of all circuits.

### Finding the data

To create this index I am going to need to combine a few datasets. I will need data about the circuits that includes their length, number of corners, height elevation, top speed etc. To better show how difficult a track is I will also seek out a dataset containing all safety cars deployed and their reason for each track. 

I am interested to see how the safety car dataset will influence the result as you could argue that a track that has more safety cars is more difficult. Finally I will attempt to find a dataset containing time penalties given to drivers, specifically track limit penealties. This occurs when all four tyres cross the white line markings of the track edge, possibily indicating a higher difficulty.


- Data Sources
1. <a href="https://mintlify.wiki/TracingInsights/RaceData/introduction">RaceData</a>
2. <a href="https://www.kaggle.com/datasets/kishan305/formula-1-circuits-1950-present">Kaggle - Formula 1 Circuits (1950 - Present)</a>


**Race Data** is a comprehensive Formula 1 race data from 1950 to present. They provide 18 data tables that will provide me with safety car, red flags and fatal accident data.

**Kaggle** Although RaceData does provide a dataset on all circuits I have opted to use this kaggle dataset as there is more technical information about each track in it.

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

all_circuits = pd.read_csv("data/all_f1_circuits.csv")
all_circuits.head()

,Circuit,City,Country,Track Length (km),Turns,Direction,Circuit Type,First Grand Prix,Last Grand Prix,Races,Best Lap Timing,Best Lap Driver,Best Lap Year,Best Lap Time
0,Brands Hatch,Fawkham,United Kingdom,4.207,9,Clockwise,Race,1964 British Grand Prix,1986 British Grand Prix,14,1:09.593,Nigel Mansell,1986,69.593
1,AVUS,Berlin,Germany,8.300,4,Anti clockwise,Road,1959 German Grand Prix,1959 German Grand Prix,1,2:04.500,Tony Brooks,1959,124.500
2,Autodromo Internazionale Enzo e Dino Ferrari,Imola,Italy,4.909,19,Anti clockwise,Race,1980 Italian Grand Prix,2025 Emilia Romagna Grand Prix,32,1:15.484,Lewis Hamilton,2020,75.484
3,Autódromo Juan y Oscar Gálvez,Buenos Aires,Argentina,4.259,19,Clockwise,Race,1953 Argentine Grand Prix,1998 Argentine Grand Prix,20,1:11.220,Emerson Fittipaldi,1973,71.220
4,Autodromo Internazionale del Mugello,Scarperia e San Piero,Italy,5.245,15,Clockwise,Race,2020 Tuscan Grand Prix,2020 Tuscan Grand Prix,1,1:18.833,Lewis Hamilton,2020,78.833

In [6]:
safety_cars = pd.read_csv("data/safety_cars.csv")
safety_cars.head()

                         Race          Cause  Deployed  Retreated  FullLaps
0    1973 Canadian Grand Prix       Accident        33       39.0         5
1   1993 Brazilian Grand Prix  Accident/Rain        29       38.0         8
2     1993 British Grand Prix   Stranded car        38       40.0         1
3  1994 San Marino Grand Prix       Accident         1        6.0         4
4     1995 Belgian Grand Prix           Rain        28       33.0         4

In [7]:
red_flags = pd.read_csv("data/red_flags.csv")
red_flags.head()

,Race,Lap,Resumed,Incident,Excluded
0,1950 Indianapolis 500,138,N,Rain.,NaN
1,1971 Canadian Grand Prix,64,N,Mist.,NaN
2,1973 British Grand Prix,2,Y,"Crash involving Jody Scheckter, Jean-Pierre Be...","Jody Scheckter, Jean-Pierre Beltoise, George F..."
3,1974 Brazilian Grand Prix,32,N,Rain.,NaN
4,1975 Spanish Grand Prix,29,N,Crash of Rolf Stommelen which killed five spec...,NaN

In [8]:
fatal_accidents_drivers = pd.read_csv("data/fatal_accidents_drivers.csv")
fatal_accidents_drivers.head()

,Driver,Age,Date Of Accident,Event,Car,Session
0,Cameron Earl,29.0,6/18/52,NaN,ERA,Test
1,Chet Miller,50.0,5/15/53,1953 Indianapolis 500,Kurtis Kraft,Practice
2,Charles de Tornaco,26.0,9/18/53,1953 Modena Grand Prix,Ferrari,Practice
3,Onofre Marimón,30.0,7/31/54,1954 German Grand Prix,Maserati,Practice
4,Mario Alborghetti,26.0,4/11/55,1955 Pau Grand Prix,Maserati,Race